spring:
  h2:
    console:
      enabled : true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username : sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: local
    include:
      - jwt
      - oauth2
cloud:
  aws:
    s3:
      bucket: haru4cut
      stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
logging:
  level:
    org.hibernate.SQL: debug
